---
- name: Install {{ POSTGRES_NAME }} development dependencies
  vars:
    ansible_python_interpreter: /usr/bin/python
  package:
    name:
      - gcc
      - git
      - systemd-devel
      - docbook-dtds
      - docbook-simple
      - docbook-slides
      - docbook-style-dsssl
      - docbook-style-xsl
      - docbook-utils
      - docbook-utils-pdf
  become: yes
- name: Create the {{ POSTGRES_NAME }} source directory {{ POSTGRES_SRC }}
  file:
    name: "{{ POSTGRES_SRC }}"
    state: directory
    owner: "{{ USER_NAME }}"
  become: yes
- name: Clone the {{ POSTGRES_NAME }} source code
  git:
    repo: "{{ POSTGRES_REPO }}"
    dest: "{{ POSTGRES_SRC }}"
    version: "{{ POSTGRES_TAG }}"
- name: Configure the {{ POSTGRES_NAME }} application
  shell: "./configure --with-openssl --with-libxml --with-libxslt --with-systemd --with-selinux --prefix={{ POSTGRES_OPT }}"
  args:
    chdir: "{{ POSTGRES_SRC }}"
    creates: "{{ POSTGRES_SRC }}/bootstrap"
#- name: Boostrap the {{ POSTGRES_NAME }} application
#  shell: ./bootstrap
#  args:
#    chdir: "{{ POSTGRES_SRC }}"
#    creates: "{{ POSTGRES_SRC }}/bootstrap"
#- name: Compiles the {{ POSTGRES_NAME }} application
#  shell: make
#  args:
#    chdir: "{{ POSTGRES_SRC }}"
#    creates: "{{ POSTGRES_SRC }}/bin/cmake"
#- name: Installs the {{ POSTGRES_NAME }} application
#  shell: make install
#  become: yes
#  args:
#    chdir: "{{ POSTGRES_SRC }}"
#    creates: "/usr/local/bin/cmake"
#  register: cmakeinstall
#- name: Update ldconfig
#  shell: ldconfig
#  become: yes
#  when: cmakeinstall.changed
#- name: Install {{ POSTGRES_NAME }} development dependencies
#  package:
#    name: [postgresql-server]
#  become: yes
#- name: Initialize the database
#  shell: /usr/bin/postgresql-setup initdb
#  args:
#    creates: /var/lib/pgsql/data/pg_hba.conf
#  become: yes
#- name: Start and enable the {{ POSTGRES_NAME }} service.
#  service:
#    name: "{{ POSTGRES_SERVICE }}"
#    enabled: yes
#    state: started
#  become: yes

