---
- name: Check if psql command exists
  stat:
    path: /usr/bin/psql
  register: PSQL_EXISTS
- name: Install {{ POSTGRES_NAME }} development dependencies
  package:
    name: [postgresql-server]
  become: yes
  when: not PSQL_EXISTS.stat.exists
- name: Initialize the database
  shell: /usr/bin/postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/pg_hba.conf
  become: yes
- name: Start and enable the {{ POSTGRES_NAME }} service.
  service:
    name: "{{POSTGRES_SERVICE}}"
    enabled: yes
    state: started
  become: yes
