---
- name: "Install pip dependencies for python: {{ PIP_DEPENDENCIES | join(' ') }}"
  ansible.builtin.pip:
    name: "{{ PIP_DEPENDENCIES }}"
- name: "Install dependencies as root: {{ POSTGRES_DEPENDENCIES | join(' ') }}"
  package:
    name: "{{ POSTGRES_DEPENDENCIES }}"
  become: true
  register: INSTALL_DEPENDENCIES
  ignore_errors: true
  when: ansible_pkg_mgr != 'homebrew'
- name: "Install dependencies as user {{ POSTGRES_USER }}: {{ POSTGRES_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ POSTGRES_DEPENDENCIES }}"
  when: ansible_pkg_mgr != 'homebrew' and INSTALL_DEPENDENCIES.failed
- name: Install {{ POSTGRES_NAME }} development dependencies for MacOSX
  vars:
    ansible_python_interpreter: /usr/bin/python
  package:
    name: "{{ POSTGRES_DEPENDENCIES }}"
    state: present
  become: false
  when: ansible_pkg_mgr == 'homebrew'
  ignore_errors: true
- name: Create the {{ POSTGRES_NAME }} source directory {{ POSTGRES_SRC }}
  file:
    name: "{{ POSTGRES_SRC }}"
    state: directory
- name: Create the {{ POSTGRES_NAME }} opt directory {{ POSTGRES_OPT }}
  file:
    name: "{{ POSTGRES_OPT }}"
    state: directory
- name: Create the {{ POSTGRES_NAME }} bin directory {{ POSTGRES_PREFIX }}/bin
  file:
    name: "{{ POSTGRES_PREFIX }}/bin"
    state: directory
- name: Clone the {{ POSTGRES_NAME }} source code into {{ POSTGRES_SRC }}
  git:
    repo: "{{ POSTGRES_REPO }}"
    dest: "{{ POSTGRES_SRC }}"
    version: "{{ POSTGRES_TAG }}"
    depth: "1"
- name: "Configure the {{ POSTGRES_NAME }} application for Linux: ./configure --with-openssl --with-libxml --with-libxslt --with-systemd{{ ' --with-selinux' if ansible_distribution_file_variety == 'RedHat' else '' }} --prefix={{ POSTGRES_OPT }}"
  shell: "./configure --with-openssl --with-libxml --with-libxslt --with-systemd{{ ' --with-selinux' if ansible_distribution_file_variety == 'RedHat' else '' }} --prefix={{ POSTGRES_OPT }}"
  args:
    chdir: "{{ POSTGRES_SRC }}"
    creates: "{{ POSTGRES_SRC }}/GNUmakefile"
  when: ansible_pkg_mgr != 'homebrew'
- name: Configure the {{ POSTGRES_NAME }} application for MacOSX
  shell: "./configure --prefix={{ POSTGRES_OPT }}"
  args:
    chdir: "{{ POSTGRES_SRC }}"
    creates: "{{ POSTGRES_SRC }}/GNUmakefile"
  when: ansible_pkg_mgr == 'homebrew'
- name: Make the {{ POSTGRES_NAME }} application for Linux
  shell: make
  args:
    chdir: "{{ POSTGRES_SRC }}"
    creates: "{{ POSTGRES_SRC }}/src/bin/psql/psql"
  when: ansible_pkg_mgr != 'homebrew'
- name: Make the {{ POSTGRES_NAME }} application world for Linux
  shell: make world
  args:
    chdir: "{{ POSTGRES_SRC }}"
    creates: "{{ POSTGRES_SRC }}/src/bin/psql/psql"
  when: ansible_pkg_mgr != 'homebrew'
- name: Make the {{ POSTGRES_NAME }} application for MacOSX
  shell: make install
  args:
    chdir: "{{ POSTGRES_SRC }}"
    creates: "{{ POSTGRES_SRC }}/src/bin/psql/psql"
  when: ansible_pkg_mgr == 'homebrew'
- name: Install the {{ POSTGRES_NAME }} application
  shell: make install
  args:
    chdir: "{{ POSTGRES_SRC }}"
    creates: "{{ POSTGRES_OPT }}/bin/psql"
  when: ansible_pkg_mgr != 'homebrew'
- name: Create the psql binary symbolic link. 
  file:
    src: "{{ POSTGRES_OPT }}/bin/psql"
    dest: "{{ POSTGRES_OPT | dirname | dirname }}/bin/psql"
    state: link

- name: Create the {{ POSTGRES_NAME }} data directory {{ POSTGRES_DATA }}. 
  file:
    name: "{{ POSTGRES_DATA }}"
    state: directory
    mode: 0700
- name: Initialize the database
  shell: "{{ POSTGRES_OPT }}/bin/initdb -D {{ POSTGRES_DATA }}"
  args:
    creates: "{{ POSTGRES_DATA }}/pg_hba.conf"
- name: Create the systemd service directory {{ POSTGRES_SYSTEMD | dirname }}
  file:
    name: "{{ POSTGRES_SYSTEMD | dirname }}"
    state: directory
  when: ansible_pkg_mgr != 'homebrew' and (ansible_distribution_file_variety != 'RedHat' or (ansible_distribution_major_version | int) > 7)
- name: Create the {{ POSTGRES_NAME }} systemd service {{ POSTGRES_SYSTEMD }}. 
  template:
    src: app_systemd.service
    dest: "{{ POSTGRES_SYSTEMD }}"
  when: ansible_pkg_mgr != 'homebrew'
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
- name: Reload the services. 
  systemd:
    daemon_reload: true
    scope: "{{ 'system' if ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 else 'user' }}"
  when: ansible_pkg_mgr != 'homebrew'
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
- name: Start and enable the {{ POSTGRES_NAME }} service. 
  service:
    name: "{{ POSTGRES_SERVICE }}"
    enabled: true
    state: restarted
    scope: "{{ 'system' if ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 else 'user' }}"
  when: ansible_pkg_mgr != 'homebrew'
  become: "{{ ansible_distribution_file_variety == 'RedHat' and (ansible_distribution_major_version | int) <= 7 }}"
- name: Create the {{ POSTGRES_NAME }} launchd service.
  template:
    src: app_launchd.service
    dest: "~/Library/LaunchAgents/org.postgresql.plist"
  when: ansible_pkg_mgr == 'homebrew'
- name: Load the {{ POSTGRES_NAME }} launchd service.
  shell: launchctl load ~/Library/LaunchAgents/org.postgresql.plist
  when: ansible_pkg_mgr == 'homebrew'
- name: Start the {{ POSTGRES_NAME }} launchd service.
  shell: launchctl start org.postgresql
  when: ansible_pkg_mgr == 'homebrew'
  changed_when: false

